# jekyll configuration
# --------------------
auto: true
server: true
permalink: /blog/:year/:month/:day/:title
pygments: true

# custom configuration
# --------------------
url: http://bitvunit.codescape.de
