permalink:  /blog/:year/:month/:day/:title  # urls generated for permalinks
auto:       true                            # regnerate when files are changed
pyments:    true                            # code highlight with pygments
server:     true                            # start server hosting _site directory
