# urls generated for permalinks
permalink:  /blog/:year/:month/:day/:title
# regnerate when files are changed
auto:       true
# code highlight with pygments
pyments:    true
# start server hosting _site directory
server:     true
